---

    name: On Commit python pep8
    
    on:
        push:
            branches:
                - development
            paths:
                - '**.py'
    
        workflow_dispatch:
    
    jobs:
      python_lint:
        runs-on:
          - ubuntu-latest
        steps:
        
          - name: Github checkout
            uses: actions/checkout@v4

          - name: Python Lint
            run: |
              sudo apt-get update -y
              sudo apt-get install -y python3-pip git libkrb5-dev
              pip3 install --upgrade pip 
              pip3 install --upgrade pycodestyle
              python3 -B -m pycodestyle --config=~${work}.config/pycodestyle ${work}tools/python/test.py

