---
    name: On Commit Terraform code

    on:
        push:
            branches:
                - development
            paths:
                - '**.tf'
        
        workflow_dispatch:

    jobs:
        lint:
            runs-on: ubuntu-latest
        
            steps:
              - name: Checkout code
                uses: actions/checkout@v2
        
              - name: Install tflint
                run: |
                  wget https://github.com/terraform-linters/tflint/releases/download/v0.30.0/tflint_linux_amd64.zip
                  unzip tflint_linux_amd64.zip
                  sudo mv tflint /usr/local/bin/
        
              - name: Terraform Init
                run: terraform init
        
              - name: Terraform Validate
                run: terraform validate
        
              - name: Terraform Lint
                run: tflint

