---

    name: On Commit python pep8
    
    on:
        push:
            branches:
                - development
            paths:
                - '**.py'
    
        workflow_dispatch:
    
    jobs:
      container_build:
        runs-on:
          - ubuntu-latest
        concurrency: "container_build"
        steps:
        
          - name: Github checkout
            uses: actions/checkout@v4
    
          - name: Build Docker image
            run: docker build -t python_vm ./tests
    
      python_int:
        runs-on:
          - ubuntu-latest
        needs: container_build
        steps:
    
          - name: Python Lint
            run: >-
              docker run
              -v $(pwd):/work
              -w /work
              python_vm python3 -B -m pycodestyle --config=/work/.config/pycodestyle /work
    