---

    name: On Commit python pep8
    
    on:
        push:
            branches:
                - development
            paths:
                - '**.py'
    
        workflow_dispatch:
    
    jobs:
      python_lint:
        runs-on:
          - ubuntu-latest
        steps:
        
          - name: Github checkout
            uses: actions/checkout@v4
    
          # - name: Build Docker image
          #   run: docker build -t python_vm ./tests

          - name: Python Lint
            run: |
              sudo apt-get update -y
              sudo apt-get install -y python3-pip git libkrb5-dev
              pip3 install --upgrade pip 
              pip3 install --upgrade pycodestyle
              echo $work
              ls $work
              python3 -B -m pycodestyle --config=~/.config/pycodestyle ~/tools/create_project_terraform_dir_structure.py

